module.exports = {
	extends: ['@commitlint/config-conventional'],
	rules: {
		'scope-enum': [
			2,
			'always',
			[
				'demos',
				'root',
				'astro-contact-form',
				'astro-cookies-api',
				'astro-js-404-page',
				'astro-js-favicon',
				'astro-js-location-map',
				'astro-js-middleware',
				'astro-js-non-html-route',
				'astro-prerender-comment-form',
				'astro-js-sass-styling',
				'astro-js-tutorial',
				'astro-mux-player',
				'astro-qr-code-generator',
				'astro-self-hosted-fonts',
				'astro-scroll-to-anchor',
				'astro-vanilla-extract',
				'getting-started-astro',
				'temporal-api-duration',
				'temporal-api-time-zones',
			],
		],
		'scope-empty': [2, 'never'],
	},
};
