#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm run prettier:check

pnpm --filter astro-capsize-font-fallbacks lint:css
pnpm --filter astro-contact-form lint:css
pnpm --filter astro-cookies-api lint:css
pnpm --filter astro-js-404-page lint:css
pnpm --filter astro-js-location-map lint:css
pnpm --filter astro-js-middleware lint:css
pnpm --filter astro-js-non-html-route lint:css
pnpm --filter astro-js-sass-styling lint:scss
pnpm --filter astro-js-tutorial lint:css
pnpm --filter astro-mux-player lint:css
pnpm --filter astro-prerender-comment-form lint:css
pnpm --filter astro-qr-code-generator lint:css
pnpm --filter astro-scroll-to-anchor lint:css
pnpm --filter astro-self-hosted-fonts lint:css
pnpm --filter getting-started-astro lint:css
pnpm --filter temporal-api-duration lint:css
pnpm --filter temporal-api-time-zones lint:css
