#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm --filter astro-contact-form check
pnpm --filter astro-contact-form check:svelte
pnpm --filter astro-js-404-page check
pnpm --filter astro-js-favicon check

