#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm --filter astro-contact-form check
pnpm --filter astro-contact-form check:svelte
pnpm --filter astro-js-404-page check
pnpm --filter astro-js-favicon check
# pnpm --filter astro-js-location-map check
pnpm --filter astro-js-location-map check:svelte
pnpm --filter astro-js-non-html-route check
pnpm --filter astro-js-sass-styling check
pnpm --filter astro-mux-player check
pnpm --filter astro-scroll-to-anchor check
pnpm --filter astro-self-hosted-fonts check
# pnpm --filter getting-started-astro check
pnpm --filter temporal-api-duration check
pnpm --filter temporal-api-time-zones check

