#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm run prettier:check

pnpm --filter astro-contact-form lint:css
pnpm --filter astro-js-404-page lint:css
pnpm --filter astro-js-location-map lint:css
pnpm --filter astro-js-non-html-route lint:css
